### ISSUE TITLE
Countries Aren't Loading

### ISSUE THREAD

**Issue by glenndarwis** [emcrisostomo/EMCCountryPickerController#18]
When installing via Cocoapods the controller isn't finding the countries.plist in the Pods folder. Is there a workaround for this?

**Comment by glenndarwis** [comment]
For some reason Pod/Resources isn't being read. It can't find the Resources folder.

**Comment by emcrisostomo** [comment]
This problems appears to be fixed by [PR#17][pr].  I'll update the POD ASAP.

[pr]: https://github.com/emcrisostomo/EMCCountryPickerController/pull/17

**Comment by glenndarwis** [comment]
Awesome. Thank you so much.

**Comment by emcrisostomo** [comment]
You're welcome.  I'm forwarding the thanks to @Ricardo1980, who contributed #17.
