### ISSUE TITLE
RTL languages support [Enhancement]

### ISSUE THREAD

**Issue by RajChanchal** [emcrisostomo/EMCCountryPickerController#24]
As you have already included locale support, that's great. Now, we expect support for RTL languages too. That includes following enhancements:
1. Flip UI
2. Search text field placeholder text should be in locale language
3. Cancel button of search field should be in locale language
4. 'No results' should be in locale language
5. Currently it is not searching as per locale, it should search if somebody has given a preferred locale.

**Comment by emcrisostomo** [comment]
That's certainly a nice set of features, but I'm not maintaining this repository. Feel free to submit a PR.
