### ISSUE TITLE
iOS13 - 'UISearchDisplayController is no longer supported

### ISSUE THREAD

**Issue by daniebruwer** [emcrisostomo/EMCCountryPickerController#27]
Terminating app due to uncaught exception 'NSGenericException', reason: 'UISearchDisplayController is no longer supported when linking against this version of iOS. Please migrate your application to UISearchController.'

**Comment by meharabPigeon** [comment]
Did you get any solution regarding this?

**Comment by daniebruwer** [comment]
@meharabPigeon we're currently using a forked version of another picker https://github.com/wyobi/ADCountryPicker

**Comment by emcrisostomo** [comment]
I'm afraid this project is not kept up to date.

**Comment by emcrisostomo** [comment]
There was a PR already solving this issue, @meharabPigeon. It should be fixed now. I've just bumped the pod to `1.4.0`. Let me know if that works.
